export default [
  {
    productId: 1234,
    productName: "Gray Athletic Cotton Socks",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 2345,
    productName: "Intermediate Size Basketball",
    paymentStatus: "Refunded",
    shipping: "Declined",
  },
  {
    productId: 3456,
    productName: "Adults Plain Cotton T-Shirt",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 4567,
    productName: "2 Slot Toaster - Black",
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    productId: 5678,
    productName: "6 Piece White Dinner Plate Set",
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    productId: 6789,
    productName: "6-Piece Nonstick",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 7890,
    productName: "Plain Hooded Fleece Sweatshirt",
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    productId: 8901,
    productName: "Luxury Towel Set - Graphite Gray",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 9012,
    productName: "Liquid Laundry Detergent",
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    productId: 1234,
    productName: "Waterproof Knit Athletic Sneakers",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 2345,
    productName: "Women's Chiffon Beachwear Cover Up - Black",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 3456,
    productName: "Round Sunglasses",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 4567,
    productName: "Women's Two Strap Buckle Sandals - Tan",
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
  {
    productId: 5678,
    productName: "Blackout Curtains Set 4-Pack - Beige",
    paymentStatus: "Refunded",
    shipping: "Declined",
  },
  {
    productId: 6789,
    productName: "Men's Slim-Fit Summer Shorts",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productId: 7890,
    productName: "Electric Glass",
    paymentStatus: "Refunded",
    shipping: "Declined",
  },
  {
    productId: 8901,
    productName: "Ultra Soft Tissue 2-Ply - 18 Box",
    paymentStatus: "Paid",
    shipping: "Delivered",
  },
];
